version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - add-apt-repository ppa:cncf-buildpacks/pack-cli
      - apt-get update -y
      - apt-get install -y pack-cli
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ${ecrSubCommand} get-login-password --region ${awsRegion} | docker login --username AWS --password-stdin ${ecrUrl}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - pack build ${imageName}:latest --path . --builder ${builder} --env NODE_ENV="production"
      - imageTags=(${imageTags}) && for tag in "$${imageTags[@]}";
        do
          docker tag ${imageName}:latest ${ecrUrl}/${imageName}:$tag;
        done
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - imageTags=(${imageTags}) && for tag in "$${imageTags[@]}";
        do
          docker push ${ecrUrl}/${imageName}:$tag;
        done
