version: 0.2

env:
  shell: bash
  parameter-store:
    dockerhubPassword: ${dockerhubPasswordKey}

phases:
  install:
    commands:
      - (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.34.2/pack-v0.34.2-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ${ecrSubCommand} get-login-password --region ${awsRegion} | docker login --username AWS --password-stdin ${ecrUrl}
      - echo Logging in to DockerHub...
      - echo $${dockerhubPassword} | docker login --username ${dockerhubUsername} --password-stdin
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - pack build ${imageName}:latest --path . --builder ${builder} --env NODE_ENV="production"
      - imageTags=(${imageTags}) && for tag in "$${imageTags[@]}";
        do
          docker tag ${imageName}:latest ${ecrUrl}/${imageName}:$tag;
        done
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - imageTags=(${imageTags}) && for tag in "$${imageTags[@]}";
        do
          docker push ${ecrUrl}/${imageName}:$tag;
        done
